### PR TITLE
Add ability to have shorthand destructuring for default function parameter objects

### PR DESCRIPTION
**Pull request by lunaruan**
Fixes [this](https://github.com/benjamn/ast-types/issues/348) issue

### CODE REVIEW

**Comment by lunaruan** [comment]
@benjamn Did you have a chance to look at this? Thanks!

**Comment by doochik** [comment]
Any chance to see this merged?

**Comment by eventualbuddha** [comment]
@benjamn can you do a release? Or give me npm access?

**Comment by benjamn** [comment]
Released as `recast@0.18.3`: http://npmjs.org/package/recast

@eventualbuddha Just added you as a maintainer: https://www.npmjs.com/package/recast/access (though please let me know if you plan to do anything unusual). Thanks for help!

**Comment by eventualbuddha** [comment]
Thanks @benjamn. I’m assuming I’ll mostly be doing bug fix releases, pretty typical.

**Pull request merged**
