### PR TITLE
Support the export-default-from syntax

### PR DESCRIPTION
**Pull request by cangoektas**
The printer has a problem with the export-default-from syntax.

Instead of printing this:

```js
export foo, { bar } from 'foo';
```

we get this:

```js
export { foo, bar } from 'foo';
```

This PR adds a failing test for that case. (#480)

@benjamn I'm not really experienced with AST's but if this doesn't require too many changes and you think a beginner could tackle it, I'd try my best if you could point me to the relevant parts of the code 😊

### CODE REVIEW

**Comment by benjamn** [comment]
If you want to give it a try, I would run `npm run debug` to enable the inspector, and then set a breakpoint in `printExportDeclaration` [here](https://github.com/benjamn/recast/blob/1648a2147e1d64f44635172e417d547094d3bf58/lib/printer.js#L2568) to see what happens.

Now that I think about it, there's a good chance `printExportDeclaration` isn't even getting called in this case, because the specifier child nodes are getting reprinted in place, so you might want to set a breakpoint in the `ExportDefaultSpecifier` printer case [here](https://github.com/benjamn/recast/blob/1648a2147e1d64f44635172e417d547094d3bf58/lib/printer.js#L506) as well.

If the child specifier is getting reprinted by itself, without triggering reprinting of the parent `export` declaration, then my guess would be that `canReprint` is `true` on [this line](https://github.com/benjamn/recast/blob/1648a2147e1d64f44635172e417d547094d3bf58/lib/patcher.js#L323) in `findArrayReprints`, since `exportDecl.specifiers` is an array, and the `ExportDefaultSpecifier` is an element of that array.

So here's my hint: if you can get `canReprint` to be `false` when a specifier changes types (from `ExportSpecifier` to `ExportDefaultSpecifier`), then `findArrayReprints` will return `false` and the whole `export` declaration should get reprinted, resulting in the desired output.

**Comment by cangoektas** [comment]
Hey @benjamn, thanks a lot for the hints!

It turns out the `printExportDeclaration` function didn't handle the case with the `ExportDefaultSpecifier` and would always put curly braces around the specifiers.

I was able to fix this but I think it's a bit of a stupid implementation. I didn't fully get the concept of Lines and how to handle the FastPath objects. If you have any ideas on how to improve this, I'm all ears :)

**Comment by benjamn** [comment]
@cangoektas I think this is a great start, and a correct diagnosis of the problem. If you want to check your implementation of `printExportDeclaration`, have a look at [the printer case for `ImportDeclaration`](https://github.com/cangoektas/recast/blob/cd35847148ea17c191747f4b72b84823be7d6e19/lib/printer.js#L511), which deals with some of the same issues (braced and unbraced specifiers).

**Comment by cangoektas** [comment]
Hey @benjamn, sorry I couldn't get back earlier. I plan on continuing with this on the weekend. One thing I didn't understand fully with the `ImportDecleration` is this part: https://github.com/cangoektas/recast/blob/cd35847148ea17c191747f4b72b84823be7d6e19/lib/printer.js#L543

Does it handle the case where imports span across multiple lines? And recast tries to preserve that formatting? Is there a test for such cases that I can look up?

**Comment by benjamn** [comment]
Right, that code checks if the line would be "too long" if printed without line breaks, and adds line breaks if so. Once this logic is executing (because this part of the AST node was sufficiently modified), the `ImportDeclaration` is going to be reprinted, according to the rules of the pretty-printer, so there's no special effort to infer or preserve the original style. This code is just trying to do something reasonable depending on how many specifiers there are.

**Comment by cangoektas** [comment]
Hey @benjamn, I think I got it. Also added another export statement to cover that case with line-breaks. Does this look good to you?

**Comment by cangoektas** [comment]
Hey @benjamn, did you had time to review this? Is there anything else I can do?

**Pull request merged**
