### PR TITLE
Fix printing class methods

### PR DESCRIPTION
**Pull request by cpojer**
The kind of MethodDefinition changed from init to method in ast-types. This fixes the printer.

### CODE REVIEW

**Comment by benjamn** [comment]
Maybe let's preserve backwards compatibility with `kind:"init"`?

**Comment by cpojer** [comment]
I don't think that's necessary – unless you are using an old version of ast-types with a new version of recsat (assuming no one creates nodes manually)?

**Comment by benjamn** [comment]
Right, but `recast.print` is supposed to work with any reasonable AST, not just ones generated by `ast-types`.

**Comment by cpojer** [comment]
Alright, made it backwards compatible :)

**Pull request merged**
