### PR TITLE
Surround arrow functions with parenthesis when binding

### PR DESCRIPTION
**Pull request by mdebbar**
Fixes the critical, long standing issue: #264 
Also fixes https://github.com/lebab/lebab/issues/105

### CODE REVIEW

**Comment by benjamn** [comment]
Though this implementation appears to work (and I thank you for submitting it), the right place to fix problems with parentheses is [`FastPath.prototype.needsParens`](https://github.com/benjamn/recast/blob/cbdb59b4fa081f1dfd7f7477bb4e98040d5e5178/lib/fast-path.js#L179), specifically [this case](https://github.com/benjamn/recast/blob/cbdb59b4fa081f1dfd7f7477bb4e98040d5e5178/lib/fast-path.js#L328).

Adding logic to `needsParens` ensures that we get the parentheses right not just for pretty-printed code, but for any reprinted code, e.g. if an arrow function gets moved from somewhere in the original AST where it didn't need parentheses to a position where it needs parentheses.

Can you move the logic to `needsParens` (and keep the tests)?

**Comment by mdebbar** [comment]
Updated, sir! 🙂
Thanks for suggesting the right way to do it.

**Comment by shajith** [comment]
@benjamn: Could this be merged/tagged? Looking for a fix for the referenced lebab/lebab#105

Thanks!

**Comment by shajith** [comment]
@benjamn: Thank you!

**Pull request merged**
