### PR TITLE
Fix needsParens for `ArrowFunctionExpression`'s as callees

### PR DESCRIPTION
**Pull request by juliankrispel**
Basically if the left hand expression of a callexpression is an arrow function we get this invalid output (when using `printGenerically`):

```js
()=>{}();
```

this output is invalid what it should be is:

```js
(()=>{})();
```

this pr fixes it and adds a spec for regressions.

cc @benjamn

### CODE REVIEW

**Comment by juliankrispel** [comment]
PING @eventualbuddha

**Comment by eventualbuddha** [comment]
Seems good to me, but I haven't been too involved in recast development for a while.

**Comment by juliankrispel** [comment]
Ah whoops sorry @eventualbuddha I was meant to ping @benjamn of course :D

**Comment by juliankrispel** [comment]
@benjamn ping :) <3

**Comment by benjamn** [comment]
Looks good to me!

**Comment by juliankrispel** [comment]
@benjamn thanks <3

**Pull request merged**
