### PR TITLE
Support tsx files with exported typescript parser

### PR DESCRIPTION
**Pull request by evans**
Adding the jsx plugin provides the ability to parse typescript files containing jsx syntax. See https://github.com/facebook/jscodeshift/issues/180#issuecomment-399618290 for more color.

### CODE REVIEW

**Comment by benjamn** [comment]
Thanks for this, @evans! Those test failures seem relevant, though. I had thought that JSX conflicted with some TypeScript `<type>` syntax, or I would have enabled it by default.

**Comment by eventualbuddha** [comment]
This seems unlikely to move forward, so I’m closing it. Consumers of recast can easily add the jsx plugin if they like.

**Comment by kube** [comment]
It's a little bit sad to see that this was closed.

TSX has some syntax conflicts with generic type parameters (e.g. `const fn = <T>(t: T) => t`), but it is worked around in TypeScript by specifying extension (`.tsx` vs `.ts`).

Maybe we could reopen the PR, and just define it as a new parser.

I know that I can define plugins manually, but it was really close here.

For the parser name IMO it should be `typescriptReact`:

Screenshot 2022-04-19 at 03 02 02

**Comment by kube** [comment]
Sorry, after trying, indeed there are collisions between syntaxes as the current PR defines plugins.

**Pull request closed without merging**
