### PR TITLE
Enable ES2015+ syntax in Recast implementation via Babel 6

### PR DESCRIPTION
**Pull request by benjamn**
It's pretty ironic that Recast has supported ES2016+ syntax in transformed code for more than two years, but its own implementation is still plain ES5! I think it's time Recast caught up with itself. Selfishly, I also know the new syntax is going to make maintaining this project much more enjoyable for me.

### CODE REVIEW

**Comment by jamestalmage** [comment]
@benjamn 
My only thought would be to move the old contents of `index.js` to `main.js`, and then have this in index.js:

```js
require('babel-core/register');
require('./main');
```

Then people can set the require hook the way they want it for their own lib and just do:

```js
require('recast/main');
```

To bypass your babel hook if they know they have already loaded up Babel or are running on some future Node version that has all the ES6 features natively.

**Comment by benjamn** [comment]
@jamestalmage that's a good idea

**Comment by benjamn** [comment]
I'm only doing `require("babel-core/register")` in the tests, though… did you mean `require("babel-polyfill")`?

**Comment by jamestalmage** [comment]
oops, saw `index.js` and skipped right over which folder it was in.

I'm assuming you are going to publish transpiled results then?

**Comment by benjamn** [comment]
Yep, I'll publish the `lib/` directory in addition to the `src/` directory (trying to follow [my own advice](http://benjamn.github.io/empirenode-2015/#/73)).

**Comment by benjamn** [comment]
Dropping support for Node versions earlier than 4 turned out to be more effective on this front.

**Pull request closed without merging**
