### PR TITLE
Add test for printer double comments bug.

### PR DESCRIPTION
**Pull request by briandipalma**
Adding a test for double comments bug. The comments are being double in the `Patcher` class but I'm not sure what the root issue is.

### CODE REVIEW

**Comment by benjamn** [comment]
Perfect, thanks! I'll take a look at this today.

**Comment by briandipalma** [comment]
Hi, is there some way to shortcircuit the performance improvements? I've tried setting `original` to undefined on the program nodes and it still seems to be printing the comments where they used as opposed to where the AST says the should be. Performance isn't a concern for me, the AST is correct when I look at it in the debugger so I was curious if there was some to make recast thing this is a fresh AST with no history?

**Comment by benjamn** [comment]
Try `recast.prettyPrint(ast).code`?

**Comment by briandipalma** [comment]
Umm, `prettyPrint` seems to strip away all the comments. I guess I can manually move the comments around for the moment.

**Pull request merged**
