### PR TITLE
feat: recast:esprima supports jsx

### PR DESCRIPTION
**Pull request by shuerguo999**
recast esprima supports jsx

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Thanks! Could you add a test that would fail without this change?

**Comment by shuerguo999** [comment]
Ok， here is a demo:

`const recast = require('recast');
const code = '
    class Square extends React.Component {
        render() {
            return (
                <button className="square">
                    {this.props.value}
                </button>
            );
        }
    }';
const ast = recast.parse(code);`

Error message:

> throw this.unexpectedTokenError(token, message);
                ^
Error: Line 5: Unexpected token <
    at ErrorHandler.constructError

**Comment by eventualbuddha** [comment]
> Ok, here is a demo.

Thanks, could you add it to the branch as a test?

**Comment by eventualbuddha** [comment]
I ended up adding esprima to the existing JSX tests that were only exercising babel. They all passed except for the last one, which illustrated that [esprima does not support JSX fragments](https://github.com/jquery/esprima/issues/2020). I disabled that test for esprima, but it's likely to be an issue for anyone attempting to use esprima with JSX.

**Comment by eventualbuddha** [comment]
Released in v0.19.0

**Pull request merged**
