### PR TITLE
Adds support for ObjectTypeSpreadProperty

### PR DESCRIPTION
**Pull request by 0x24a537r9**
Turns out ast-types already has support, so it was mainly updating the dep and adding tests (with flow-parser, because esprima-fb does not recognize the fairly new Flow syntax).

### CODE REVIEW

**Comment by keyanzhang** [comment]
Here's the syntax: facebook/flow#3534

Seems we haven't documented it yet but it's been used intensively at FB. :)

**Comment by 0x24a537r9** [comment]
Aside: I also have a PR ready to send out to update recast to the next (and latest) version of ast-types after this with the last 2 commits of https://github.com/0x24a537r9/recast/commits/opaque-types

**Comment by 0x24a537r9** [comment]
@benjamn Should be a pretty quick review, and I've got another stacked and ready to go :)

**Comment by benjamn** [comment]
@0x24a537r9 Ok, I'll try to look at this first thing tomorrow! Feel free to ping again if I drop the ball.

**Comment by benjamn** [comment]
Released as part of [`recast@0.12.7`](https://github.com/benjamn/recast/releases/tag/v0.12.7).

**Pull request merged**
