### PR TITLE
Update printer.ts to support `kind = 'get'/'set'` on `TSMethodSignature`

### PR DESCRIPTION
**Pull request by dandean**
`TSMethodSignature` has a `kind` property which can be set to `method` (the default), `get`, and `set`. When `get` and `set`, the method is a getter or a setter, and as such, should be prefixed with either `get ` or `set `.

### CODE REVIEW

**Comment by coderaiser** [comment]
Could you please add test for this? Or provide code example

**Comment by coderaiser** [comment]
Added tests https://github.com/benjamn/recast/pull/1401 and landed in [`@putout/recast@1.16.0`](https://github.com/putoutjs/recast/releases/tag/v1.16.0)

**Comment by dandean** [comment]
@coderaiser Apologies for the delayed response, and thank you for adding the tests!

**Comment by coderaiser** [comment]
Some checks are failing in my PR, so if you fix this in your PR, I think it can make things go a bit faster :)...

**Review by eventualbuddha — APPROVED** [review]

**Comment by eventualbuddha** [comment]
Published in v0.23.8.

**Pull request merged**
