### PR TITLE
Fix/quote print options

### LINKED ISSUE #1023: Quotes are broken in recast v0.21.0
After updating I see that:

```js
const { parse, print} = require("recast");
const {StringLiteral, ExpressionStatement}= require('@babel/types');

const ast = parse(`const a = 5`, {
    parser: require("recast/parsers/babel")
});

ast.program.body.unshift(ExpressionStatement(StringLiteral('strict mode')));

console.log(print(ast, {
    quote: 'single',
}));
```

Produces

```js
PrintResult { code: '"strict mode";\nconst a = 5' }
```

And `quote` option is ignored.

`recast v0.20.0` produces:

```js
PrintResult { code: "'strict mode';\nconst a = 5" }
```

The problem begins from this commit: https://github.com/benjamn/recast/commit/8e542935d0fd1e7265e00c4946514aa9d181e114

### PR DESCRIPTION
**Pull request by coderaiser**
Fixes #1023

### CODE REVIEW

**Comment by ElonVolo** [comment]
This broke one of my unit tests and applying it to the fork a recast fixed the problem. @benjamn, you should consider merging this.

**Comment by cos** [comment]
Second this, would be great if merged.

**Comment by coderaiser** [comment]
@cos just use [`@putout/recast`](https://github.com/putoutjs/recast).

**Comment by eventualbuddha** [comment]
Fixed in v0.21.3.

**Comment by cos** [comment]
Excellent, thanks!

**Pull request merged**
