### PR TITLE
Inexact printing

### PR DESCRIPTION
**Pull request by jbrown215**
Flow added an inexact flag to the ObjectTypeAnnotation node. When it is true, the object should have a `...` at the end of its props list. See  https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf

### CODE REVIEW

**Comment by pvdz** [comment]
Ping @benjamn 
Can you please have a look at this PR? I'll soon put up another two PRs to fix printing types (the heuristics for applying parenthesis and colons are a bit off). But this one is becoming important as well.

Alternatively, can we discuss an an option where one of us was added as a collaborator to this project, with write-access?

**Comment by pvdz** [comment]
@jbrown215 could you have a look and resolve the merge conflicts, make sure everything is up to date and ready to merge?

**Comment by jbrown215** [comment]
Happy to resolve conflicts after @benjamn confirms that he'll be able to take a look at this. Otherwise, I'd prefer to wait until he has time for me to put in the effort.

**Comment by benjamn** [comment]
I will take care of rebasing and cleaning up this code, while preserving authorship of the original commits. I'm not inclined to share write access with anyone who thinks rebasing a single-hunk 15-line patch is too much to ask, or that asking a maintainer to share access is appropriate when a PR with obvious merge conflicts sits unmerged. When @pvdz @-mentioned me on twitter about this, I thought, "Great, they must have fixed the merge conflicts, and everything is ready to go, pending my approval." Imagine my disappointment when I found out nothing had changed!

**Comment by jbrown215** [comment]
Thank you for taking care of this, and sorry to have disappointed you. I also realized my previous comment can be read with a negative tone, but I really meant that I know that you have important work to do that isn't maintaining this repo, the same way that I have work that is completely unrelated to this PR.

Your comment here is the only thing I've heard on this PR since I put it up in October, so I figured this (understandably) wasn't a priority for you. This PR is also not blocking anything I'm currently working on, which is why I didn't ping you myself. Even if it was incorrect, I hope you can understand my apprehension to prioritize this PR over my other work.

Either way, thank you for the lesson in open source etiquette. I'm new here, so I genuinely appreciate it.

**Comment by pvdz** [comment]
#thanks! :)

**Pull request merged**
