### PR TITLE
Make comments node configurable. Issue #151

### PR DESCRIPTION
**Pull request by briandipalma**

### CODE REVIEW

**Comment by benjamn** [comment]
Let's make it `writable: true` too, so that you don't have to use `Object.defineProperty` to change it.

**Comment by jugglinmike** [comment]
I'm having trouble modifying comments, either through re-setting the property wholesale (with this path applied) or through modifying the properties of the object created by Recast. In either case, `recast.print` retains the comments in original form when I pass the ast to `recast.print`. I can't find an example of (or test for) comment modification in this project, so I'm not sure if I'm missing something or if this is not a supported feature. Can anyone advise?

**Comment by benjamn** [comment]
@jugglinmike That's a bug that I've just recently become aware of, and it's my top priority now: https://github.com/benjamn/recast/issues/153. Thanks for speaking up about it.

**Comment by jugglinmike** [comment]
@benjamn Thanks for being on top of it :)

**Comment by briandipalma** [comment]
Sorry, I made this PR before starting work so I've not been able to respond but I'm also experiencing the issues @jugglinmike has mentioned. I was planning to write some tests to show the failure before raising the bug :)

Looks like you are already on it anyway!

**Pull request merged**
