### PR TITLE
Fix indentation to handle nodes that cross multiple lines, and the lines are at different indent levels.

### PR DESCRIPTION
**Pull request by asselin**
This is for issue #230

### CODE REVIEW

**Comment by benjamn** [comment]
Want to add some tests?

**Comment by asselin** [comment]
The tests all fail on Windows (I suspect probably a line ending issue).  I'll take a look at that first, and then at tests.  Any suggestions on what you'd like to see in the way of tests?

**Comment by asselin** [comment]
So yes, \n vs \r\n is what's causing the tests to fail on Windows.  What's your preference on how this should be fixed?  A couple of options are:

1. Add the lineTerminator option to every print call.  e.g.

````
var printOptions = {
    lineTerminator: "\n"
};
recast.print(dup.body, printOptions).code
````

2. Change every place that concatenates lines together to create "expected" to use the OS line terminator.  e.g.

````
var eol = require("os").EOL;
var code = trailing.join(eol);
````

Personally, I think option 2 is a better choice.  It's cleaner in the code, and to me it more closely tests what the library is supposed to be doing.

@benjamn What's your opinion?

**Comment by benjamn** [comment]
I agree that option 2 is better, since it exercises more of the parsing/printing logic. Can Travis run tests on Windows automatically?

**Comment by asselin** [comment]
Looks like Travis supports only Mac and Linux.  https://github.com/travis-ci/travis-ci/issues/216

I'll submit a PR for option 2 later today

**Comment by benjamn** [comment]
That would be great, thanks!

**Comment by eventualbuddha** [comment]
Closing since this never got tests added.

**Pull request closed without merging**
