### PR TITLE
Print parens for nullable union/intersection types

### PR DESCRIPTION
**Pull request by keyanzhang**
Add parens for types like `?(string | number)`. Thanks!

### CODE REVIEW

**Comment by benjamn** [comment]
Would it make sense to add this logic to [`FastPath.prototype.needsParens`](https://github.com/benjamn/recast/blob/5c6bf309e7d5bb7618e04b3fd4b07010537b1c0f/lib/fast-path.js#L179)?

**Comment by keyanzhang** [comment]
@benjamn cool, should I just call `maybeAddParens` then?

**Comment by benjamn** [comment]
You shouldn't have to call `maybeAddParens` explicitly, since the `print` function in `genericPrintNoParens` goes through all that logic for you. That's my intention, at least.

If I'm right, you should only have to `return true` from `FastPath#needsParens` when the node is a `UnionTypeAnnotation` or `IntersectionTypeAnnotation` and the parent node is a `NullableTypeAnnotation`.

**Comment by keyanzhang** [comment]
Thanks @benjamn. I added 
```js
    case "IntersectionTypeAnnotation":
    case "UnionTypeAnnotation":
        return parent.type === "NullableTypeAnnotation";
```
as new top-level cases in `#needsParens` but seems these cases are not reached. Am I missing something here?

My new `NullableTypeAnnotation` case in `printer`:
```js
    case "NullableTypeAnnotation":
        return concat([
            "?",
            path.call(print, "typeAnnotation")
        ]);
```

**Comment by keyanzhang** [comment]
I added a diff (https://github.com/benjamn/recast/pull/293/commits/bf190cdb8239e387398520d50ab5e1762bf6198f) to show my failed attempt. Thanks!

**Comment by benjamn** [comment]
[Here](https://github.com/benjamn/recast/blob/1c9725db83e8fe15ca9b2671bdc0a6f52fb74f79/lib/fast-path.js#L195-L198)'s the culprit. Can you change that check to exclude `Statement` nodes rather than allowing only `Expression` nodes?

**Comment by keyanzhang** [comment]
Fixed, thanks!

**Comment by keyanzhang** [comment]
When you have time, could you also bump the `ast-types` dep to `0.8.18` while releasing a new version? Thanks! 😃

**Pull request merged**
