### PR TITLE
Add support for `TSInstantiationExpression`

### PR DESCRIPTION
**Pull request by eventualbuddha**
Refs #1230

See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiation-expressions. This won't work yet because `ast-types` does not yet know about `TSInstantiationExpression`. Once it does `recast` will need to be updated to include the newer release of `ast-types`, at which point it will be supported.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
@benjamn I can make a PR for `ast-types` for you to review, or you can give me write+publish access. Your call.

**Comment by benjamn** [comment]
@eventualbuddha Thanks for offering to do the `ast-types` part too! I'm happy to give you write/publish access, but I've realized the `ast-types` repo is not in good shape for local development right now (`npm i` fails, and that's not all), so I'd like to fix that before asking anyone else to work on that project. I should have a PR up tomorrow.

**Comment by benjamn** [comment]
@eventualbuddha Here's the PR I promised, though it happens to be an existing PR where @octogonz had already done most of the work! https://github.com/benjamn/ast-types/pull/327#issuecomment-1334573349

I will probably merge that PR soon, which should fix `npm install` and make it possible to add new defs again. If you still have time to add a def for `TSInstantiationExpression`, please give it a try, and let me know if you hit any snags.

**Comment by iliakan** [comment]
bump =)

**Comment by benjamn** [comment]
Progress! https://github.com/benjamn/ast-types/pull/886

**Comment by benjamn** [comment]
Based on those [test failures](https://github.com/benjamn/recast/actions/runs/3670598533/jobs/6205246283) (newly [itemized](https://github.com/benjamn/recast/pull/1232/commits/62ffa684b7023d20daf9dad6831bab1df237abb1)!), we still need to implement pretty-printer `switch (node.type)` cases for the following the following AST types:
- [ ] [`ClassAccessorProperty`](https://github.com/babel/babel/blob/f5b52208f05157a348fdfaa0222c07a9a83fb101/packages/babel-generator/src/generators/classes.ts#L123-L166)
- [ ] [`TSTypeCastExpression`](https://github.com/babel/babel/blob/b84f4f2d69228010f86baf82d107728b860bca9d/packages/babel-generator/src/generators/typescript.js#L376-L379) (possibly no longer used?)
- [ ] [`TSSatisfiesExpression`](https://github.com/babel/babel/blob/f5b52208f05157a348fdfaa0222c07a9a83fb101/packages/babel-generator/src/generators/typescript.ts#L525-L541)

**Comment by benjamn** [comment]
@eventualbuddha Wanna try implementing the pretty-printer case for [`ClassAccessorProperty`](https://github.com/babel/babel/blob/f5b52208f05157a348fdfaa0222c07a9a83fb101/packages/babel-generator/src/generators/classes.ts#L123-L166)? If not, or you run out of time, just let me know and I'll finish it up.

**Comment by eventualbuddha** [comment]
Alright, I got most of the way to a pretty-printer implementation for `ClassAccessorProperty` but hit an issue. In Babel, the AST can represent a "definite" property as in this TypeScript code:

```ts
class Foo {
  accessor bar!: unknown;
}
```

However, `ast-types` is unaware of the `definite` field for this node so the type checking fails:

```
test/printer.ts:1311:15 - error TS2345: Argument of type '{ key: types.namedTypes.Identifier; definite: boolean; }' is not assignable to parameter of type '{ abstract?: boolean | undefined; accessibility?: "public" | "private" | "protected" | null | undefined; comments?: CommentKind[] | null | undefined; computed?: boolean | undefined; ... 7 more ...; value: ExpressionKind; }'.
  Object literal may only specify known properties, and 'definite' does not exist in type '{ abstract?: boolean | undefined; accessibility?: "public" | "private" | "protected" | null | undefined; comments?: CommentKind[] | null | undefined; computed?: boolean | undefined; ... 7 more ...; value: ExpressionKind; }'.

1311               definite: true,
                   ~~~~~~~~~~~~~~
```

What do you think, @benjamn?

**Comment by benjamn** [comment]
@eventualbuddha Can you try updating to `ast-types@0.16.1` (just published), which includes https://github.com/benjamn/ast-types/pull/891?

**Comment by eventualbuddha** [comment]
@benjamn alright, added a commit to update `ast-types` and a small refactor to consolidate printing of class member modifiers.

**Review by benjamn — APPROVED** [review]

**Comment by benjamn** [comment]
Running `npm i recast@next` will give you version 0.23.1 (or later), which includes this change.

Thanks to @eventualbuddha for tackling this PR and for getting that final test passing.

If everything looks good here, I will tag this version as `latest` on npm in a few days.

**Pull request merged**
